### PR TITLE
Feat: add content for Seragam Pramuka

### PR DESCRIPTION
**Pull request by novalkrnfds**
Hi @mazipan, please review this pull request for issue #27. Thank you! :rocket:

### CODE REVIEW

**Comment by mazipan** [comment]
Hmmm kok, di preview nya gak kelihatan ya?

**Comment by novalkrnfds** [comment]
Ok, Mas.

**Comment by novalkrnfds** [comment]
Sudah ada di preview ya, Mas.

**Review by mazipan — APPROVED** [review]
Oke nih mas 👍

**Pull request merged**
