### PR TITLE
chore: trying migrate to preact

### PR DESCRIPTION
**Pull request by adibfirman**
Trying moving to Preact related with this PR #39 , so these screenshots will compare of the bundle size, and Preact was making me surprised 😎 it cut half of each file size

Using React
image

Using Preact
image

### CODE REVIEW

**Review by mazipan — APPROVED** [review]
Looks good

**Comment by mazipan** [comment]
Is the fast refresh on the local still works @adibfirman ?

**Comment by adibfirman** [comment]
> Is the fast refresh on the local still works @adibfirman ?

ahh, thanks for reminding me mas, apparently this doesn't work, will be fixing it asap

**Comment by adibfirman** [comment]
@mazipan ahh, thanks for reminding me mas, i just check on the build process its working as well, but on the dev process, the fast refresh not working as well, so i will trying to fix it

**Comment by mazipan** [comment]
Maybe need to look this issue https://github.com/vercel/next.js/issues/13969

**Comment by adibfirman** [comment]
@mazipan thanks for the reference issue mas, will look it 🙏

**Comment by adibfirman** [comment]
mas @mazipan I just pushed a new commit, which I do a downgrade on nextjs version to 9.5.3, and it's working while dev and build itself, and preact working as well

**Review by mazipan — APPROVED** [review]

**Pull request merged**
