### PR TITLE
feat: Add Vercel Cache config

### PR DESCRIPTION
**Pull request by adylanrff**
Add `vercel.json` config to the root project directory. Currently it only contains the `Header `
Currently I use `86400` for the max-age. 

Please review 🙏 
ps: This is my first Vercel related PR, inputs are very welcomed

### CODE REVIEW

**Comment by adylanrff** [comment]
Hi @mazipan can you authorize the deployment for this PR? As per this documentation, I want to see from the `X-Vercel-Cache` whether it is working well or not

image

**Review by mazipan — APPROVED** [review]
Looks good

**Comment by mazipan** [comment]
Let me know if you finish testing ya

**Comment by adylanrff** [comment]
image

Apparently the cache seems to always miss. I need to dive deeper into this. (Or is there any mechanism that I dont know of?)

**Comment by mazipan** [comment]
How about `Cache-Control` header? Can you see it?

https://vercel.com/docs/configuration#project/headers

**Comment by adylanrff** [comment]
> How about `Cache-Control` header? Can you see it? @adylanrff
> 
> https://vercel.com/docs/configuration#project/headers

Yes, I could, but it shows `max_age=0` which means the config apparently does not override the default one.

**Comment by mazipan** [comment]
I already check using https://httpstatus.io/

Screenshot_20201019-191313_Chrome

**Review by mazipan — APPROVED** [review]

**Pull request merged**
